name: venv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - sqlite>=3.49.1
  - pip
  - poetry
  - jupyter
  - ipykernel
  - ipywidgets
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - adjusttext
  - scikit-learn
  - pytorch
  - torchvision
  - keras
  - tensorflow
  - opencv
  - sqlalchemy
  - flask
  - jinja2
