name: venv
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.12
  - sqlite>=3.49.1
  - pip
  - jupyter
  - ipykernel
  - ipywidgets
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - adjusttext
  - scikit-learn
  - pytorch
  - torchvision
  - sqlalchemy
  - flask
  - jinja2
  - fastqc
  - multiqc
  - fastp
  - trimmomatic
  - samtools
  - hisat2
  - subread
  - htseq
  - pydeseq2
  - gseapy
  - mygene
  - goatools
